# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
