# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_auto_20170610_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='withdraw_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='withdraw_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Failed', 'Failed'), ('Deleted', 'Deleted'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Reversed', 'Reversed'), ('Escrowed', 'Escrowed'), ('Released', 'Released'), ('Disputed', 'Disputed'), ('Expired', 'Expired')], default='Pending', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
