# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_escrow_tx_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='tx_code',
        ),
    ]
