# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='log',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='everything.Recipe'),
        ),
    ]
