# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0002_auto_20170123_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextInput',
            new_name='Text',
        ),
    ]
