# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import everything.models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0004_auto_20170123_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=everything.models.get_image_path)),
            ],
        ),
    ]
