# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
